### ISSUE TITLE
Didn't finish downloading video

### ISSUE THREAD

**Issue by moodiest** [drawrowfly/instagram-scraper#10]
I just encountered an odd issue where the video download suddenly stopped.

I was running the command: `instatouch user thechefartsmith -d -t all -c 1` and at 42% the video stopped downloading and it outputted the metadata to files and the video was not outputted. This was the video - https://www.instagram.com/p/CAbHOnZB6mE/

![image](https://user-images.githubusercontent.com/10815538/82525018-49f4d280-9b28-11ea-9fda-ceed08a7776a.png)

**Comment by drawrowfly** [comment]
IG can interrupt the connection from their side. When i have more free time i will rewrite this tool in Go or Rust and it will be more stable
