### ISSUE TITLE
Date error on getting posts

### ISSUE THREAD

**Issue by vivek-hb** [drawrowfly/instagram-scraper#12]
When I get posts based on username I get the following error
InstaTouch Scraper StartedError: Can't scrape date. Please try again or submit issue to the github.
Kindly look into this issue.

**Comment by anurastogi** [comment]
> When I get posts based on username I get the following error
> InstaTouch Scraper StartedError: Can't scrape date. Please try again or submit issue to the github.
> Kindly look into this issue.

I am facing the same error on my production environment - Ubuntu 16.04.5. Though it is working on my local Windows machine. Please guide.

**Comment by drawrowfly** [comment]
You need to use session value. Between june 2-5 IG has changed something and it can detect non residential IP and will require from you to be logged in. If you are using it as module you can set session id value through option **session**

Login to your IG in browser->open inspector->network->choose any request to the IG and look for value in cookies that is starting with **sessionid**

In scraper set option session: "sessionid=BLABLALBA"

**Comment by anurastogi** [comment]
> You need to use session value. Between june 2-5 IG has changed something and it can detect non residential IP and will require from you to be logged in. If you are using it as module you can set session id value through option **session**
> 
> Login to your IG in browser->open inspector->network->choose any request to the IG and look for value in cookies that is starting with **sessionid**
> 
> In scraper set option session: "sessionid=BLABLALBA"

I tried this piece of code 
```
 const options = { count: 20,session: "sessionid=GOT_FROM_COOKIES" };
 const user = await instatouch.user(_profileName_, options);
```
However, I am still getting the same error on the Ubuntu machine. On Windows , its working well.
Anything I am missing?

**Comment by anurastogi** [comment]
On the Terminal, the hashtag, comments, likers options are working. It is only the "user" option which is giving the error.

**Comment by drawrowfly** [comment]
Because if you are not authorized to the IG in the browser and will visit any IG Profile in the browser by using proxy or spammed IP, IG will ask for you to sign in to your account

**Comment by drawrowfly** [comment]
It is a new form of protection. You can use valid session value(preferably more then 1)  and it will work fine. 

I will check on it later, maybe there is another way

**Comment by danarenepotter** [comment]
I am on a Mac and "In scraper set option session: "sessionid=BLABLALBA" " worked to fix this bug for me! Thanks much
