### ISSUE TITLE
Sudden problem

### ISSUE THREAD

**Issue by gladenko** [drawrowfly/instagram-scraper#22]
No i have this

Error: Can't scrape date. Please try again or submit issue to the github

Before today all is ok now i have this error.

I try with vpn but nothing. 

It seems want login!

**Comment by gladenko** [comment]
Found solution it work only with public ip not in nat?

**Comment by drawrowfly** [comment]
Use private ipv4 proxy + session(can be taken from the browser session) and everything will work fine
