### ISSUE TITLE
Can only get 40 Likes or Comments per post scrape

### ISSUE THREAD

**Issue by ravenfish** [drawrowfly/instagram-scraper#24]
Hi there, I've just realised the **likers** and **comments** features downloads a CSV that caps out at 40 entries (plus header row). Not sure how to amend this, but thought it might be similar to another person that mentioned a 1050 cap.

**Comment by ravenfish** [comment]
I'm thinking it could be down to the scrolling function of the likes and comments, so this might not be an issue, just something I might have to try and tweak.

**Comment by drawrowfly** [comment]
Hello

I don't see any issues, i can easily execute this method without any problems, and in the example below extract 400 users who liked that post, same goes for the comments

const res = await likers('https://www.instagram.com/p/CFyoqZTDLkt/', {
      count: 400,
});
