### ISSUE TITLE
Can't scrape data in instatouch user proxy

### ISSUE THREAD

**Issue by neosce** [drawrowfly/instagram-scraper#25]
When trying to instatouch user natgeo -p 'user: password@11.111.111.11: 1010' it throws a _Scrape can't date error_, but when using likers 'B7wOyffArc5' the proxy works. Was this by design?

**Comment by drawrowfly** [comment]
When you use proxy you also need to set an active session so that instagram will give you access to the user page

Update to instatouch@2.3.0 and use --session to set session id

Session can be extract from the browser with inspector tool

Session id example: sessionid=BLBLBLBLLBL
