### ISSUE TITLE
CSV output limited to 52 rows

### ISSUE THREAD

**Issue by erwanx1** [drawrowfly/instagram-scraper#28]
Hi I am trying to output the post information of a user but the maximum output is 52 rows.

eg. `instatouch user natgeo -c 100 -t ` gives me 52 instead of 100. Have tried using proxies as well.

**Comment by drawrowfly** [comment]
I will update the app shortly

**Comment by deann88** [comment]
I notice this issue happens with -t 'json' as well. Is there any instagram API limitation that we are hitting, or are you already working on fixing it? 

Thanks

**Comment by drawrowfly** [comment]
#16

**Comment by jacekpoplawski** [comment]
What was the solution? I see same problem here https://github.com/drawrowfly/instagram-scraper/issues/29
