### ISSUE TITLE
likers doesn't work?

### ISSUE THREAD

**Issue by jacekpoplawski** [drawrowfly/instagram-scraper#29]
I have problem getting likers for the post, I tried this example:

instatouch likers https://www.instagram.com/p/B3XPst_A98M/ -c 200 -t csv

and there is no output at all, other types of requests work

**Comment by drawrowfly** [comment]
They do work but you need to provide an active session (from instagram web)

You can do that by using module, currently it is impossible by using CLI

I will update app shortly and you will be able to set session through the CLI

**Comment by arnaldoperez** [comment]
I'm running the sample of "likers" and is not working either. Is there any other configuration I may need to setup?
This is my code:

`const instaTouch = require('instatouch');

(async () => {
    try {
        const options = { count: 1 };
        console.log({options})
        const likers = await instaTouch.likers('B7wOyffArc5', options);
        console.log(likers);
    } catch (error) {
        console.log(error);
    }
})();`

**Comment by jacekpoplawski** [comment]
@drawrowfly in the meantime could you publish working example how to use likers with module?

**Comment by drawrowfly** [comment]
1. https://github.com/drawrowfly/instagram-scraper#get-session-id
2. In the cli use option --session "sessionid=BLAHBLAHBLAH"
3. In the module {
.....
session: "sessionid=BLAHBLAHBLAH"
}

**Comment by jacekpoplawski** [comment]
Thank you - it works as you described! 👍 
However, I only receive 50 likers, how to get all?

**Comment by drawrowfly** [comment]
Documentation Documentation

**Comment by jacekpoplawski** [comment]
hmm... I can't find anything more about limits than "-c" but it is already set to 200 in my example. I tested "-c 20" and it works - I get 20 likers. But max is 50, can't get more.
