### ISSUE TITLE
InstaTouch Scraper StartedError: Can't scrape date.

### ISSUE THREAD

**Issue by ColtraneNadler** [drawrowfly/instagram-scraper#38]
```
InstaTouch Scraper StartedError: Can't scrape date. Please try again or submit issue to the github
    at InstaTouch.extractData (/usr/local/lib/node_modules/instatouch/build/core/InstaTouch.js:372:27)
    at async InstaTouch.startScraper (/usr/local/lib/node_modules/instatouch/build/core/InstaTouch.js:149:13)
    at async promiseScraper (/usr/local/lib/node_modules/instatouch/build/entry.js:112:20)
    at async startScraper (/usr/local/lib/node_modules/instatouch/bin/cli.js:36:25)
```

**Comment by everdeen7336** [comment]
I have the same issue too.

**Comment by jacekpoplawski** [comment]
same here

**Comment by sannajammeh** [comment]
Same here

**Comment by sannajammeh** [comment]
Instagram seems to limit non session calls to their graphql endpoints. I added a session id to the options and it worked.

**Comment by abdelhaqs** [comment]
Hello @sannajammeh, 
I want to scrap posts data, but I'm still getting only 50 posts ( 50 rows of data in the csv ) 
Where did put the session id exactly, that's what I did in my case

`instatouch user cnn -c 150 --session=177776760e7-56156d`

![image](https://user-images.githubusercontent.com/13757404/107119031-3a1f4900-6885-11eb-871b-647e1031ea3e.png)

**Comment by boscacci** [comment]
Y'all, I just figured something out

The way the code is written, you have to set `--session="sessionid=loremipsum"` 🤦‍♂️ 

I.e. include the string `"sessionid="` in the value for `--session` and it'll work, until fixed

**Comment by drawrowfly** [comment]
Set session

**Comment by sgnofx** [comment]
> Instagram seems to limit non session calls to their graphql endpoints. I added a session id to the options and it worked.

hey man can you give the proper syntax for it
