### ISSUE TITLE
How to get my followers and following accounts

### ISSUE THREAD

**Issue by JoanJosep33** [drawrowfly/instagram-scraper#39]
Hello. First of all, nice program.

I would like to know (I didn't found on the examples) **how can I get the list of followers and following people from my account**. Would you mind to tell me how could I get them? 

Thanks.

**Comment by drawrowfly** [comment]
Scrape users who liked specific post REQUIRES AN ACTIVE SESSION
Scrape followers REQUIRES AN ACTIVE SESSION
Scrape following REQUIRES AN ACTIVE SESSION

**Comment by apathre** [comment]
You can use the following methods:-

instatouch.followers('<username>',options)

and

instatouch.following('<username>',options)

options to always include sessionid
(How to mention sessionid in options -> This can be found in the documentation for options)
(How to find sessionid -> Each time you log in to instagram.com, Instagram saves cookies. This cookie document contains session id. You can find sessionid by checking cookie data for Instagram saved on your browser)

Hope it helps

**Comment by vishakhag6** [comment]
Hi, 
I am also trying to scrape the followers of a user and running this following command:

`instatouch followers vishakhaoriginals sessionid=34892121557%3AD8ja1zaXHcBz6t%3A29`
But no output. Can you help pls?
