### ISSUE TITLE
Not getting comments or likers

### ISSUE THREAD

**Issue by ntoniocp** [drawrowfly/instagram-scraper#40]
I can't get any comments or likers. I tried passing different ammount of options with different values of count parameter, different posts and even tried with the id of the posts and the urls.

Using the module directly i get an object with 0 results and using the cli it doesn't show anything after the string that indicates that the scrapper is running. 🤔

**Comment by Tefor** [comment]
Same problem here, just getting 38 comments

**Comment by rmclain** [comment]
You need to use the `--session sessionid=XYZ` found in the cookies section in chrome/safari/etc.
