### ISSUE TITLE
What does "rate limited" mean?

### ISSUE THREAD

**Issue by SKAE5** [drawrowfly/instagram-scraper#5]

**Comment by drawrowfly** [comment]
When you make to many request in short period of time from the same ip

**Comment by SKAE5** [comment]
Ah ok get it. How many requests can I do in a short period of time?
Can I get an unlimited version of the code?

**Comment by drawrowfly** [comment]
The code it self is not limited and etc. Rate Limit error is from Instagram, just user proxy
