### ISSUE TITLE
Getting error: InstaTouch Scraper StartedError: Can't scrape date. Please try again or submit issue to the github

### ISSUE THREAD

**Issue by vishakhag6** [drawrowfly/instagram-scraper#54]
Hi, 
I am getting this error. Also, how can I scrape the followers of a user? 

Thanks,

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/instagram-scraper#get-session-id

**Comment by vishakhag6** [comment]
Hi, 
I am running this command in terminal i.e. 
instatouch user instagram -c 5 --session=177776760e7-56156

But still getting the same error. Let me know if I am passing in wrong way.
