### ISSUE TITLE
How can I scrape the followers of a user?

### ISSUE THREAD

**Issue by vishakhag6** [drawrowfly/instagram-scraper#55]
Hi, 
Need to scrape all the followers of the user. Let me know how can I achieve this. Not able to find it.     

Thanks!

**Comment by drawrowfly** [comment]
Documentation is your friend

**Comment by vishakhag6** [comment]
I am going through the documentation but can not find anything from which I can scrape the followers. 
Running: 

`instatouch followers Instagram sessionid=34892145657%3AD8ja1zaXHcBz6t%3A29`

Would be very grateful, if you can guide me a little.

**Comment by vishakhag6** [comment]
> Documentation is your friend

I am going through the documentation but can not find anything from which I can scrape the followers.
Running:

instatouch followers Instagram sessionid=34892145657%3AD8ja1zaXHcBz6t%3A29

Would be very grateful, if you can guide me a little.
