### ISSUE TITLE
TypeError: Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by eghyforcoding** [drawrowfly/instagram-scraper#57]
Can this be used in React or Vue?

I got this error from one of the dependencies, graceful-fs/pollyfills.js:

TypeError: Object prototype may only be an Object or null: undefined
<img width="873" alt="Screenshot 2021-07-23 at 11 19 28 AM" src="https://user-images.githubusercontent.com/72452621/126733978-c35f00e0-604c-4828-997b-25bb70790111.png">

**Comment by drawrowfly** [comment]
only nodejs
