### ISSUE TITLE
 message: 'Can\'t scrape date. Please try again or submit issue to the github'

### ISSUE THREAD

**Issue by trentona** [drawrowfly/instagram-scraper#6]
I don't have date anywhere in the code and it seems to inconsistently give the error? Is there a way I could avoid scraping for the date?

**Comment by drawrowfly** [comment]
Soon I will completely update the package with better documentation, error outputs and etc

**Comment by trentona** [comment]
Is there a way I could remove the need for "Date"? or does that just have nothing to do with it?

**Comment by drawrowfly** [comment]
Again new version will be uploaded shortly , i don't maintain don't really have time to check old code

**Comment by drawrowfly** [comment]
new version published
