### ISSUE TITLE
Installs with tiktok-scraper as cli keyword.

### ISSUE THREAD

**Issue by moodiest** [drawrowfly/instagram-scraper#8]
When installing with npm i -g instatouch, it uses the name tiktok-scraper.
![image](https://user-images.githubusercontent.com/10815538/82523079-13688900-9b23-11ea-903f-8fa53b31be32.png)
![image](https://user-images.githubusercontent.com/10815538/82523111-1ebbb480-9b23-11ea-8fc9-12cf0050863b.png)

**Comment by drawrowfly** [comment]
Ouch. Fixed
