### ISSUE TITLE
[Feature Req] Private accounts and stories

### ISSUE THREAD

**Issue by moodiest** [drawrowfly/instagram-scraper#9]
Please could you look into using login credentials to scrape private accounts. Also the ability to scrape stories would be nice.

**Comment by drawrowfly** [comment]
It is possible if you will use it as module and set **session** value

I was thinking on adding authorization feature to a CLI but facebook is kinda against such things

**Comment by moodiest** [comment]
> It is possible if you will use it as module and set **session** value
> 
> I was thinking on adding authorization feature to the CLI but facebook is kinda against such things

Do you mean like using a cookie file? PyInstaLive generates a cookie file on your first login that it then uses for future logins. If that's what you're referring to by session value then that sounds like a good thing to do to me.
